{
 "title": "Vitastor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "label_values(clusterid)" }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leader Monitor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(vitastor_monitor_info{clusterid=\"$Cluster\"} == 1) by (monitor_hostname)",
     "legendFormat": "{{monitor_hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Standby Monitors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vitastor_monitor_info{clusterid=\"$Cluster\"} == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Raw Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vitastor_osd_size_bytes{clusterid=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Used Raw Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vitastor_osd_size_bytes{clusterid=\"$Cluster\"})-sum(vitastor_osd_free_bytes{clusterid=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(vitastor_osd_size_bytes{clusterid=\"$Cluster\"})-sum(vitastor_osd_free_bytes{clusterid=\"$Cluster\"}))*100/sum(vitastor_osd_size_bytes{clusterid=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Min Pool Space Efficiency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(vitastor_pool_space_efficiency{clusterid=\"$Cluster\"} > 0)*100"
    }
   ]
  },
  {
   "title": "Hosts Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(vitastor_osd_status{clusterid=\"$Cluster\"} > 0) by (host))"
    }
   ]
  },
  {
   "title": "Hosts Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(vitastor_osd_status{clusterid=\"$Cluster\"} < 1) by (host))"
    }
   ]
  },
  {
   "title": "OSDs Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vitastor_osd_status{clusterid=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vitastor_osd_status{clusterid=\"$Cluster\"})-sum(vitastor_osd_status{clusterid=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pools Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vitastor_pool_status{clusterid=\"$Cluster\"})-sum(vitastor_pool_status{clusterid=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pools Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vitastor_pool_status{clusterid=\"$Cluster\"} == 0)"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Client IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_read\",op_type=\"op\"}[60s])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_write\",op_type=\"op\"}[60s])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_del\",op_type=\"op\"}[60s])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_sync\",op_type=\"op\"}[60s])",
     "legendFormat": "sync"
    }
   ]
  },
  {
   "title": "Client Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op=\"primary_read\",op_type=\"op\"}[60s])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op=\"primary_write\",op_type=\"op\"}[60s])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op=\"primary_del\",op_type=\"op\"}[60s])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op=\"primary_sync\",op_type=\"op\"}[60s])",
     "legendFormat": "sync"
    }
   ]
  },
  {
   "title": "Client Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_usec{clusterid=\"$Cluster\",op=\"primary_read\",op_type=\"op\"}[60s])/rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_read\",op_type=\"op\"}[60s])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(vitastor_stat_usec{clusterid=\"$Cluster\",op=\"primary_write\",op_type=\"op\"}[60s])/rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_write\",op_type=\"op\"}[60s])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(vitastor_stat_usec{clusterid=\"$Cluster\",op=\"primary_del\",op_type=\"op\"}[60s])/rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_del\",op_type=\"op\"}[60s])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op=\"primary_sync\",op_type=\"op\"}[60s])/rate(vitastor_stat_count{clusterid=\"$Cluster\",op=\"primary_sync\",op_type=\"op\"}[60s])",
     "legendFormat": "sync"
    }
   ]
  },
  {
   "title": "Recovery IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_count{clusterid=\"$Cluster\",op_type=\"recovery\"}[60s])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Recovery Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op_type=\"recovery\"}[60s])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Scrub Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_bytes{clusterid=\"$Cluster\",op_type=\"op\",op=\"scrub\"}[60s])"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "User Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vitastor_object_bytes{clusterid=\"$Cluster\",object_type!=\"object\"}",
     "legendFormat": "{{object_type}}"
    }
   ]
  },
  {
   "title": "Active Pool Space Efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "vitastor_pool_space_efficiency{clusterid=\"$Cluster\"} * vitastor_pool_status{clusterid=\"$Cluster\"} * 100",
     "legendFormat": "{{pool_name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vitastor_pg_count{clusterid=\"$Cluster\"} > 0) by (pg_state)",
     "legendFormat": "{{pg_state}}"
    }
   ]
  },
  { "title": "OSDs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Active OSDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "vitastor_osd_status{clusterid=\"$Cluster\"}",
     "legendFormat": "{{osd_num}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "OSD Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "vitastor_osd_size_bytes{clusterid=\"$Cluster\"}-vitastor_osd_free_bytes{clusterid=\"$Cluster\"}",
     "legendFormat": "{{osd_num}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "OSD Space Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(vitastor_osd_size_bytes{clusterid=\"$Cluster\"}-vitastor_osd_free_bytes{clusterid=\"$Cluster\"})*100/vitastor_osd_size_bytes{clusterid=\"$Cluster\"}",
     "legendFormat": "{{osd_num}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "OSD Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_osd_stat_usec{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_read\"}[60s])/rate(vitastor_osd_stat_count{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_read\"}[60s]) > 0.001",
     "legendFormat": "OSD {{osd_num}}"
    }
   ]
  },
  {
   "title": "OSD Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_osd_stat_usec{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_write\"}[60s])/rate(vitastor_osd_stat_count{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_write\"}[60s]) > 0.001",
     "legendFormat": "OSD {{osd_num}}"
    }
   ]
  },
  {
   "title": "OSD Sync, Delete Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_osd_stat_usec{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_sync\"}[60s])/rate(vitastor_osd_stat_count{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_sync\"}[60s]) > 0.001",
     "legendFormat": "OSD {{osd_num}} - sync"
    },
    {
     "expr": "rate(vitastor_osd_stat_usec{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_delete\"}[60s])/rate(vitastor_osd_stat_count{clusterid=\"$Cluster\",op_type=\"op\",op=\"primary_delete\"}[60s]) > 0.001",
     "legendFormat": "OSD {{osd_num}} - delete"
    }
   ]
  },
  {
   "title": "OSD Local Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_osd_stat_usec{clusterid=\"$Cluster\",op_type=\"op\",op=\"read\"}[60s])/rate(vitastor_osd_stat_count{clusterid=\"$Cluster\",op_type=\"op\",op=\"read\"}[60s]) > 0.001",
     "legendFormat": "OSD {{osd_num}}"
    }
   ]
  },
  {
   "title": "OSD Local Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vitastor_osd_stat_usec{clusterid=\"$Cluster\",op_type=\"op\",op=~\"^(write|write_stable)$\"}[60s])/rate(vitastor_osd_stat_count{clusterid=\"$Cluster\",op_type=\"op\",op=~\"^(write|write_stable)$\"}[60s]) > 0.001) without (op)",
     "legendFormat": "OSD {{osd_num}}"
    }
   ]
  },
  {
   "title": "Average OSD Network Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(vitastor_stat_usec{clusterid=\"$Cluster\",op_type=\"subop\"}[60s])/rate(vitastor_stat_count{clusterid=\"$Cluster\",op_type=\"subop\"}[60s]) - ignoring(op_type) rate(vitastor_stat_usec{clusterid=\"$Cluster\",op_type=\"op\"}[60s])/rate(vitastor_stat_count{clusterid=\"$Cluster\",op_type=\"op\"}[60s])\n",
     "legendFormat": "{{op}}"
    }
   ]
  }
 ]
}