- name: use_perms
  type: bool
  default: false
  info: |
    Enable client permissions in a Vitastor cluster, including Antietcd built into the Monitor.
    Requires configured encryption. Also note that separate Antietcd requires separate configuration
    to use permissions (see [security documentation](../usage/security.en.md) for details).
  info_ru: |
    Включает клиентские привилегии в кластере Vitastor, в том числе во встроенном в мониторе Antietcd.
    Требует настроенного шифрования протокола. Также обратите внимание, что отдельно установленный Antietcd
    требует отдельной настройки привилегий (подробности смотрите в [документации безопасности](../usage/security.ru.md)).
- name: cert
  type: string
  info: |
    Client certificate of the current Vitastor user. Required for Vitastor protocol encryption.
    Must be signed with [client_ca](#client_ca). Also used as the client certificate for etcd/Antietcd
    connections by default.
  info_ru: |
    Клиентский сертификат текущего пользователя Vitastor. Требуется для шифрования протокола Vitastor.
    Должен быть подписан [client_ca](#client_ca). Также по умолчанию используется как клиентский
    сертификат для подключения к etcd/Antietcd и Vault.
- name: pkey
  type: string
  info: Private key of the current Vitastor user.
  info_ru: Закрытый ключ текущего пользователя Vitastor.
- name: etcd_ca
  type: string
  info: |
    Trusted TLS CA to verify etcd server certificate. Or just the etcd server's
    certificate itself - it's fine to use it for etcd_ca.
  info_ru: |
    Доверенный корневой TLS-сертификат для проверки сертификата сервера etcd.
    Либо же просто сам сертификат сервера etcd - его можно использовать как etcd_ca.
- name: client_ca
  type: string
  info: |
    Trusted TLS CA to verify Vitastor client certificates.
    Mandatory for Vitastor protocol encryption.
  info_ru: |
    Доверенный TLS-сертификат для проверки сертификатов клиентов Vitastor.
    Требуется для шифрования протокола Vitastor.
- name: osd_ca
  type: string
  info: |
    Trusted TLS CA to verify Vitastor OSD certificates. Also mandatory for Vitastor protocol
    encryption. Must be different from client_ca. May be equal to osd_cert - different OSDs
    don't require separate certificates at the moment because their permissions don't differ.
  info_ru: |
    Доверенный TLS-сертификат для проверки сертификатов OSD Vitastor. Также обязателен
    для шифрования протокола Vitastor. Должен отличаться от client_ca. Может быть равен
    osd_cert - разные OSD не требуют разных сертификатов, потому что на данный момент
    привилегии разных OSD никак не отличаются.
- name: mon_ca
  type: string
  info: |
    Trusted TLS CA to verify Vitastor Monitor certificates. Used only for separate Antietcd,
    not required when a monitor built-in Antietcd is used. May be equal to mon_client_etcd_cert.
  info_ru: |
    Доверенный TLS-сертификат для проверки сертификатов мониторов Vitastor. Используется
    только отдельно установленным Antietcd, не требуется при использовании встроенного в монитор
    Antietcd. Может быть равен mon_client_etcd_cert.
- name: antietcd_cert
  type: string
  info: Server TLS certificate for Antietcd built into the Monitor.
  info_ru: Серверный TLS-сертификат для Antietcd, встроенного в монитор.
- name: antietcd_key
  type: string
  info: Private key for antietcd_cert.
  info_ru: Закрытый ключ для сертификата antietcd_cert.
- name: etcd_proxy.urls
  type: string or array of strings
  type_ru: строка или массив строк
  info: |
    etcd URLs for Antietcd etcd proxy mode.
    See [Mon as Etcd proxy](../usage/security.en.md#mon-as-etcd-proxy) for details.
  info_ru: |
    Адреса etcd для режима Antietcd etcd-прокси.
    Смотрите подробности в разделе [Mon в роли Etcd proxy](../usage/security.ru.md#mon-в-роли-etcd-proxy).
- name: etcd_proxy.cert
  type: string
  info: Client certificate for Antietcd connections to etcd in proxy mode.
  info_ru: Клиентский сертификат для подключений от Antietcd к etcd в режиме прокси.
- name: etcd_proxy.key
  type: string
  info: Private key for etcd_proxy.cert.
  info_ru: Закрытый ключ для сертификата etcd_proxy.cert.
- name: etcd_proxy.ca
  type: string
  info: Trusted TLS CA to verify etcd server certificate when connecting to it from Antietcd.
  info_ru: Доверенный TLS-сертификат для проверки сертификата сервера etcd при подключениях от Antietcd.
- name: osd_cert
  type: string
  info: |
    Vitastor OSD server certificate. Required for Vitastor protocol encryption. May be equal
    to [osd_ca](#osd_ca) - all OSDs share the same permission set for now. Also used as the client
    certificate for connections from OSD to etcd/Antietcd by default.
  info_ru: |
    Сертификат сервера Vitastor OSD. Требуется для шифрования протокола Vitastor. Может быть равен
    [osd_ca](#osd_ca) - все OSD на данный момент имеют одинаковые привилегии. Также по умолчанию
    используется как клиентский сертификат для подключения от OSD к etcd/Antietcd.
- name: osd_pkey
  type: string
  info: Private key for osd_cert.
  info_ru: Закрытый ключ для сертификата osd_cert.
- name: api_cert
  type: string
  info: Server TLS certificate for [vitastor-cli serve](../usage/cli.en.md#serve) API server.
  info_ru: Серверный TLS-сертификат для API-сервера [vitastor-cli serve](../usage/cli.ru.md#serve).
- name: api_pkey
  type: string
  info: Private key for api_cert.
  info_ru: Закрытый ключ для сертификата api_cert.
- name: etcd_client_cert
  type: string
  info: |
    Client TLS certificate to use for connections from Vitastor clients to etcd/Antietcd if you don't want
    to use the common client certificate [cert](#cert).
  info_ru: |
    Клиентский TLS сертификат для подключений от клиентов Vitastor к etcd/Antietcd, если вы не хотите
    использовать общий клиентский сертификат [cert](#cert).
- name: etcd_client_key
  type: string
  info: Private key for etcd_client_cert.
  info_ru: Закрытый ключ для сертификата etcd_client_cert.
- name: osd_etcd_client_cert
  type: string
  info: |
    Client TLS certificate to use for connections from Vitastor OSDs to etcd/Antietcd if you don't want
    to use the common OSD certificate [osd_cert](#osd_cert).
  info_ru: |
    Клиентский TLS сертификат для подключений от Vitastor OSD к etcd/Antietcd, если вы не хотите
    использовать общий сертификат OSD [osd_cert](#osd_cert).
- name: osd_etcd_client_key
  type: string
  info: Private key for osd_etcd_client_cert.
  info_ru: Закрытый ключ для сертификата osd_etcd_client_cert.
- name: mon_etcd_client_cert
  type: string
  info: |
    Client TLS certificate to use for connections from Vitastor Monitors to etcd/Antietcd - required
    if you don't use the built-in Antietcd. In case you use it Monitor has direct access to Antietcd data
    and doesn't require any connection.
  info_ru: |
    Клиентский TLS сертификат для подключений от мониторов Vitastor к etcd/Antietcd - требуется, если
    вы не используете встроенный в монитор Antietcd. Если вы используете его, то монитор и так имеет
    прямой доступ к данным Antietcd и не требует никаких соединений.
- name: mon_etcd_client_key
  type: string
  info: Private key for mon_etcd_client_cert.
  info_ru: Закрытый ключ для сертификата mon_etcd_client_cert.
- name: proto_checksums
  type: string
  default: payload
  info: |
    One of "full", "payload", "gcm", "none":
    - "full" means calculate and verify transport level checksums from the full message data
      including the header - recommended for unencrypted setups.
    - "payload" enables checksums only for the actual read/write data, but skips them for message
      headers - recommended for encrypted setups because headers are already protected by AES-GCM.
    - "gcm" disables checksums and enables AES-GCM encryption of the whole messages including headers
      and data - AES-GCM already includes MAC which is actually a stronger checksum. This option is
      slower and is only recommended for untrusted networks.
    - "none" disables transport level checksums at all.
  info_ru: |
    Одно из значений "full", "payload", "gcm" и "none":
    - "full" означает расчёт и проверку контрольных сумм на транспортном уровне от полных сообщений,
      включая их заголовки и данные - рекомендуется для кластеров без шифрования.
    - "payload" включает контрольные суммы только для данных сообщений, но пропускает заголовки -
      такая настройка рекомендуется для кластеров с включённым шифрованием, потому что в них заголовки
      и так защищены шифрованием AES-GCM.
    - "gcm" отключает контрольные суммы и включает шифрование полных сообщений включая заголовки и
      данные - AES-GCM уже включает в себя MAC, который по сути является криптостойкой контрольной
      суммой. Такая настройка медленнее и рекомендуется только для недоверенных сетей.
    - "none" полностью отключает контрольные суммы на транспортном уровне.
- name: force_proto_checksums
  type: string
  info: |
    To allow older clients to connect to a Vitastor cluster with enabled checksums, Vitastor OSDs
    allow clients to downgrade their proto_checksums by default. force_proto_checksums sets the
    minimum security level allowed for connecting clients. When encryption is disabled, default
    force_proto_checksums is none and clients without checksums are allowed. With enabled
    encryption, force_proto_checksums becomes "payload" by default to block unauthenticated data
    on the transport level.
  info_ru: |
    Чтобы старые клиенты Vitastor могли подключаться к кластеру с включёнными контрольными
    суммами, Vitastor OSD по умолчанию разрешают клиентам отключать контрольные суммы
    данных (proto_checksums). Настройка force_proto_checksums задаёт минимальный уровень
    безопасности, разрешённый для подключающихся клиентов. Когда шифрование отключено,
    force_proto_checksums по умолчанию равно none и подключения клиентов без контрольных
    сумм разрешаются. При включённом шифровании значение по умолчанию force_proto_checksums
    становится "payload", чтобы блокировать подключения с неаутентифицированными данными.
- name: max_cipher_pool_size
  type: int
  default: 256
  info: |
    Maximum number of OpenSSL cipher contexts cached in OSD memory, counted separately
    for each cipher and for encryption/decryption. Probably doesn't require modification.
  info_ru: |
    Максимальное количество кэшируемых в памяти OSD контекстов шифра OpenSSL, учитываемое
    отдельно для каждого шифра и для шифрования и расшифровки. Вряд ли требует изменения.
- name: vault_url
  type: string
  info: |
    Vault base URL.

    Vitastor clients support AES-256-XTS image data encryption with different per-image keys.
    Encryption is performed by the client, OSDs don't have access to decrypted data.

    Encryption keys may be stored in etcd or, for the increased security level, in an external
    [HashiCorp Vault](https://developer.hashicorp.com/vault/) or [OpenBao](https://openbao.org/)
    instance.

    Vitastor clients use [v1 k/v secrets engine](https://openbao.org/api-docs/secret/kv/kv-v1/)
    and [TLS authentication engine](https://openbao.org/api-docs/auth/cert/) in Vault.

    In that case, only key IDs are stored in etcd.
  info_ru: |
    Базовый адрес Vault.

    Клиенты Vitastor поддерживают AES-256-XTS шифрование данных образов с отдельными ключами на
    каждый образ. Данные шифруются клиентами, OSD не имеют доступа к незашифрованным данным.

    Ключи шифрования могут храниться в etcd или, для повышенного уровня безопасности, во внешнем
    [HashiCorp Vault](https://developer.hashicorp.com/vault/) или [OpenBao](https://openbao.org/).

    Клиенты Vitastor используют [движок секретов v1](https://openbao.org/api-docs/secret/kv/kv-v1/)
    и [TLS-аутентификацию](https://openbao.org/api-docs/auth/cert/) в Vault.

    В этом случае, только ID ключей хранятся в etcd.
- name: vault_secret_api_path
  type: string
  default: /v1/secret/
  info: Vault v1 secret API mount path to use.
  info_ru: Путь к API секретов v1 для использования клиентами.
- name: vault_client_cert
  type: string
  info: |
    Client TLS certificate to use for Vault connections if you don't want to use the common Vitastor
    client certificate [cert](#cert) which is also used for Vault connections by default.
  info_ru: |
    Клиентский TLS сертификат для подключений к Vault на тот случай, если вы не хотите использовать
    общий сертификат клиента Vitastor [cert](#cert), используемый для подключений к Vault по умолчанию.
- name: vault_client_key
  type: string
  info: Private key for the vault_client_cert certificate.
  info_ru: Закрытый ключ для сертификата vault_client_cert.
- name: vault_ca
  type: string
  info: |
    Trusted TLS CA to verify Vault server certificate. May be path to a file,
    directory or just a PEM string with certificate.
  info_ru: |
    Доверенный корневой TLS-сертификат для проверки сертификата сервера Vault.
    Может быть путём к файлу, директории или просто строкой с сертификатом в
    формате PEM.
- name: vault_timeout_ms
  type: int
  default: 5000
  info: Timeout for Vault requests in milliseconds.
  info_ru: Максимально время выполнения Vault-запросов в миллисекундах.
- name: vault_error_timeout_sec
  type: int
  default: 60
  info: |
    Time (in seconds) to wait before retrying after receiving an error from Vault.
  info_ru: |
    Время (в секундах) для ожидания перед повторной попыткой при получении ошибки от Vault.
- name: vault_refresh_leeway_sec
  type: int
  default: 60
  info: |
    Extra time (in seconds) before real Vault token lease_timeout to refresh it, just
    in case of system clock drift.
  info_ru: |
    Зазор времени (в секундах), чтобы обновлять токены Vault чуть раньше их реального
    lease_timeout, на случай "ухода" системных часов.
